# Generated by Django 6.0.4 on 2026-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
